### ISSUE TITLE
Specifying icon size in "em" is not working

### ISSUE THREAD

**Issue by dlemmermann** [kordamp/ikonli#150]
The only "em" size that works is "1em". If I specify a number smaller than 1 then the icon does not show up at all. If I specify a number larger than 1 then I can see the icon quickly grow bigger and bigger until it disappears. The attached screenshot shows an intermediate step of this growth process.

<img width="531" alt="Bildschirmfoto 2022-03-09 um 17 38 40" src="https://user-images.githubusercontent.com/9534301/157487511-9e791bc1-9b6b-44c0-83a2-d2e3accbbe21.png">

**Comment by dlemmermann** [comment]
If you want to try it yourself simply clone my "GemsFX" project and run TagFieldApp after changing this rule: 

```css
.tags-field .graphic-wrapper .ikonli-font-icon {
    -fx-icon-size: 1.0em;
    -fx-icon-color: -fx-text-background-color;
}
```
